# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='diametro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 24, 20, 325000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='material',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
