# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0002_auto_20160418_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='orden',
        ),
        migrations.AlterField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 28, 4, 398000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Recto'), (1, 'Rollo')], default=1),
        ),
    ]
