# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0003_auto_20160418_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pieza', models.CharField(default=0, max_length=20)),
                ('calibre', models.CharField(default=0, max_length=20)),
                ('pija', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('estatus', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('fechaRegistro', models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 34, 0, 359000, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 34, 0, 359000, tzinfo=utc)),
        ),
    ]
