# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0004_auto_20160418_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('longitud', models.FloatField(default=0)),
                ('alto', models.FloatField(default=0)),
                ('ancho', models.FloatField(default=0)),
                ('estatus', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('fechaRegistro', models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 39, 2, 132000, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='despiece',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 39, 2, 127000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 39, 2, 127000, tzinfo=utc)),
        ),
    ]
