# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0006_auto_20160418_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Local'), (1, 'Foraneo')], default=1)),
                ('capacidad', models.IntegerField()),
                ('placas', models.CharField(max_length=20)),
                ('estatus', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('fechaRegistro', models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 48, 9, 864000, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='despiece',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 48, 9, 864000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 48, 9, 864000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='estructura',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 48, 9, 864000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ingenieria',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 48, 9, 864000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 17, 48, 9, 864000, tzinfo=utc)),
        ),
    ]
