# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0016_auto_20160418_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despiece',
            name='material',
        ),
        migrations.AlterField(
            model_name='despiece',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 337000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 338000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='estructura',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 339000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 341000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ingenieria',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 339000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 337000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 340000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 19, 15, 36, 340000, tzinfo=utc)),
        ),
    ]
