# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0019_despiece_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despiece',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estructura',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingenieria',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
