# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0020_auto_20160418_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despiece',
            name='material',
        ),
        migrations.AddField(
            model_name='despiece',
            name='material',
            field=models.ManyToManyField(to='control_acero.Material'),
        ),
    ]
