# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0021_auto_20160418_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='despiece',
            field=models.ManyToManyField(to='control_acero.Despiece'),
        ),
        migrations.AddField(
            model_name='estructura',
            name='elemento',
            field=models.ManyToManyField(to='control_acero.Elemento'),
        ),
    ]
