# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acero', '0115_etapa_apoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='controlasignacion',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='controlasignacion',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='controlasignacion',
            name='programaSuministro',
        ),
        migrations.RemoveField(
            model_name='controlasignacion',
            name='programaSuministroDetalle',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='EtapaDespiece',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='apoyo',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='funcionAnterior',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='material',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='taller',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='etapadescuento',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='etapadespiece',
            name='EtapaDespieceDetalle',
        ),
        migrations.RemoveField(
            model_name='etapadespiece',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='etapadespiece',
            name='material',
        ),
        migrations.RemoveField(
            model_name='etapadespiecedetalle',
            name='despiece',
        ),
        migrations.RemoveField(
            model_name='inventariofisico',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='inventariofisico',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='programasuministro',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='programasuministro',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='programasuministro',
            name='funcionHabilitado',
        ),
        migrations.RemoveField(
            model_name='programasuministrodetalle',
            name='apoyo',
        ),
        migrations.RemoveField(
            model_name='programasuministrodetalle',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='programasuministrodetalle',
            name='material',
        ),
        migrations.RemoveField(
            model_name='programasuministrodetalle',
            name='programaSuministro',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='ControlAsignacion',
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.DeleteModel(
            name='EtapaDescuento',
        ),
        migrations.DeleteModel(
            name='EtapaDespiece',
        ),
        migrations.DeleteModel(
            name='EtapaDespieceDetalle',
        ),
        migrations.DeleteModel(
            name='InventarioFisico',
        ),
        migrations.DeleteModel(
            name='ProgramaSuministro',
        ),
        migrations.DeleteModel(
            name='ProgramaSuministroDetalle',
        ),
    ]
